name: flutter_global_animations
description: A flutter plugin to play custom global animations in your application.
version: 0.1.1
repository: https://github.com/jonasroussel/flutter_global_animations
homepage: https://github.com/jonasroussel/flutter_global_animations#readme

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
